src/Partner.Surround.Admin/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;
using Abp.AspNetCore.Mvc.Authorization;
using System.Threading.Tasks;
using Partner.Surround.Admin.Models.Common;
using Partner.Surround.Social.Chat;
using Partner.Surround.Social.Chat.Dto;

namespace Partner.Surround.Admin.Controllers
{
    [AbpMvcAuthorize]
    public class ChatController : SurroundControllerBase
    {
        private readonly IChatAppService _chatAppService;

        public ChatController(IChatAppService chatAppService)
        {
            _chatAppService = chatAppService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> GetChatUserList()
        {
            var chatUserDtos = await _chatAppService.GetAllChatUser();
            return Json(new ResponseParamListViewModel<ChatUserDto>(chatUserDtos.Items));
        }

        public async Task<JsonResult> GetUnreadMessageCount()
        {
            var unreadMessageCount = await _chatAppService.UnreadMessageCount();
            return Json(new ResponseParamSingleViewModel<int>(unreadMessageCount));
        }

        public async Task<JsonResult> GetUserChatMessageList(long userId)
        {
            var userChatMessages = await _chatAppService.GetUserChatMessages(new GetUserChatMessagesInput()
            {
                UserId = userId
            });
            return Json(new ResponseParamListViewModel<ChatMessageDto>(userChatMessages.Items));
        }

        public async Task MarkAllUnreadMessagesOfUserAsRead(long userId)
        {
            await _chatAppService.MarkAllUnreadMessagesOfUserAsRead(new MarkAllUnreadMessagesOfUserAsReadInput()
            {
                UserId = userId
            });
        }
    }
}

src/Partner.Surround.Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Abp.AspNetCore.Mvc.Authorization;

namespace Partner.Surround.Admin.Controllers
{
    [AbpMvcAuthorize]
    public class HomeController : SurroundControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ChatPanel()
        {
            return View();
        }
    }
}

src/Partner.Surround.Admin/Controllers/NotificationsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using Microsoft.AspNetCore.Mvc;
using Partner.Surround.Admin.Models.Common;
using Partner.Surround.Admin.Models.Notifications;
using Partner.Surround.Notifications;
using Partner.Surround.Notifications.Dto;

namespace Partner.Surround.Admin.Controllers
{
    /// <summary>
    /// 消息管理控制器
    /// </summary>
    [AbpMvcAuthorize]
    public class NotificationsController : SurroundControllerBase
    {
        private readonly INotificationAppService _notificationAppService;

        public NotificationsController(INotificationAppService notificationAppService)
        {
            _notificationAppService = notificationAppService;
        }

        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取未读通知数量
        /// </summary>
        /// <returns></returns>
        public async Task<JsonResult> GetUnreadNotificationCount()
        {
            var unreadNotificationCount = await _notificationAppService.UnreadMessageCount();
            return Json(new ResponseParamSingleViewModel<int>(unreadNotificationCount));
        }

        /// <summary>
        /// 根据分页条件获取消息列表
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetUserNotificationList(GetUserNotificationPagedViewModel viewModel)
        {
            var input = PagedViewModelMapToPagedInputDto<GetUserNotificationPagedViewModel, GetUserNotificationsPagedInput>(viewModel);
            var pagedUserNotificationDto = await _notificationAppService.GetPagedUserNotifications(input);

            return Json(new GetNotificationsResultViewModel(pagedUserNotificationDto.TotalCount, pagedUserNotificationDto.UnreadCount, pagedUserNotificationDto.Items));
        }

        /// <summary>
        /// 设置消息记录全部已读
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SetAllNotificationsAsRead()
        {
            await _notificationAppService.SetAllNotificationsAsRead();

            return Json(new ResponseParamViewModel(L("AllNotificationSetAsReadSuccessful")));
        }

        /// <summary>
        /// 设置指定消息记录已读
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SetNotificationsAsRead([FromBody]List<EntityDto<Guid>> input)
        {
            await _notificationAppService.SetNotificationAsRead(input);

            return Json(new ResponseParamViewModel(L("NotificationSetAsReadSuccessful")));
        }

        /// <summary>
        /// 删除消息记录
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> DeleteNotification([FromBody]List<EntityDto<Guid>> input)
        {
            await _notificationAppService.DeleteNotification(input);

            return Json(new ResponseParamViewModel(L("DeleteNotificationSuccessful")));
        }
    }
}

src/Partner.Surround.Admin/Controllers/WorkSpaceController.cs
using Microsoft.AspNetCore.Mvc;
using Abp.AspNetCore.Mvc.Authorization;

namespace Partner.Surround.Admin.Controllers
{
    [AbpMvcAuthorize]
    public class WorkSpaceController : SurroundControllerBase
    {
        public ActionResult TenantConsole()
        {
            return View();
        }

        public ActionResult HostConsole()
        {
            return View();
        }
    }
}

src/Partner.Surround.Admin/Views/Home/Index.cshtml
@using Partner.Surround.Admin.Views
@using Partner.Surround.Admin.Views.Shared.Components.RightNavbarUserArea
@using Partner.Surround.Admin.Views.Shared.Components.SideBarMenu
@{
    ViewBag.Title = L("HomePage");
    ViewBag.CurrentPageName = SurroundPageName.Home;
}

@section styles{
    <link rel="stylesheet" href="~/css/load.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
}

<!-- 布局框架 -->
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        <ul class="layui-nav layui-layout-left">
            <li class="collaspe layui-nav-item"><a href="#" class="layui-icon layui-icon-shrink-right"></a></li>
            <li class="refresh layui-nav-item"><a href="#" class="layui-icon layui-icon-refresh-1" loading=600></a></li>
        </ul>
        <div id="control" class="layui-layout-control"></div>
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item layui-hide-xs"><a href="#" class="fullScreen layui-icon layui-icon-screen-full"></a></li>
            <li class="layui-nav-item layui-hide-xs"><a href="https://gitee.com/530521314/Partner.Surround" class="layui-icon layui-icon-website"></a></li>
            <li class="layui-nav-item layui-hide-xs">
                <a class="notice">
                    <i class="layui-icon layui-icon-notice"></i>
                    <span id="headerNotice"></span>
                </a>
            </li>
            @await Component.InvokeAsync(typeof(RightNavbarUserAreaViewComponent))
            <li class="setting layui-nav-item"><a href="#" class="layui-icon layui-icon-more-vertical"></a></li>
        </ul>
    </div>
    <div class="layui-side layui-bg-black">
        <div class="layui-logo">
            <img class="logo" src="" />
            <span class="title"></span>
        </div>
        @await Component.InvokeAsync(typeof(SideBarMenuViewComponent))
    </div>
    <div class="layui-body">
        <div id="content"></div>
    </div>
</div>

<!-- 移动端 遮盖层 -->
<div class="pear-cover"></div>

<!-- 初始加载 动画-->
<div class="loader-main">
    <div class="loader"></div>
</div>

<!-- 聊天组件 -->
<div id="social">
    <div class="pear-social-entrance layui-icon layui-icon-dialogue" pear-id="social"></div>
</div>

<!-- 移动端 的 收缩适配 -->
<div class="collaspe pe-collaspe layui-hide-sm">
    <i class="layui-icon layui-icon-shrink-right"></i>
</div>

@section scripts{
    <script type="text/javascript">
        layui.use(['admin', 'layer', 'hash', 'abp', 'abpsignalrclient','abpsignalrchat'], function () {
            var admin = layui.admin;
            var $ = layui.jquery;
            var layer = layui.layer;
            var hash = layui.hash;
            var abp = layui.abp;
            var interval = "";
            var chatPanelIndex = "";

            var config = {
                logo: {
                    title: "Partner Surround", // 网站标题
                    image: "/images/logo.png" // 网站Logo
                },
                menu: {
                    control: false, // 是 否 开 启 多 系 统 菜 单 true 开启 false 关闭
                    accordion: true,
                    async: false,
                    select: hash.md5("@Url.Action(!AbpSession.TenantId.HasValue ? "HostConsole": "TenantConsole", "WorkSpace")").toUpperCase(), // 默 认 选 中 菜 单 项
                },
                tab: {
                    muiltTab: true, // 是 否 开 启 多 标 签 页 true 开启 false 关闭
                    keepState: true,
                    tabMax: 20,
                    index: {
                        id: hash.md5("@Url.Action(!AbpSession.TenantId.HasValue ? "HostConsole": "TenantConsole","WorkSpace")").toUpperCase(),
                        href: '@Url.Action("TenantConsole","WorkSpace")', // 默 认 加 载 主 页
                        title: "@Html.Raw(L(!AbpSession.TenantId.HasValue ? "HostConsole": "TenantConsole"))"
                    }
                },
                theme: {
                    defaultMenu: "dark-theme", // 默 认 主 题 样 式 dark-theme 默认主题 light-theme 亮主题
                    allowCustom: true,
                    defaultColor:3
                },
                colors: [
                    {
			            id: "1",
			            color: "#FF5722"
		            },
		            {
			            id: "2",
			            color: "#5FB878"
		            },
		            {
			            id: "3",
			            color: "#1E9FFF"
                    },
                    {
			            id: "4",
			            color: "#FFB800"
                    },
                    {
			            id: "5",
			            color: "darkgray"
                    },
                    {
			            id: "6",
			            color: "#f7cfea"
		            }
                ],
                links: [
                    {
			            icon: "layui-icon layui-icon-website",
			            title: "Pear Admin网站",
			            href: "http://www.pearadmin.com"
		            },
		            {
			            icon: "layui-icon layui-icon-read",
			            title: "Abp网站",
			            href: "https://aspnetboilerplate.com/"
		            },
		            {
			            icon: "layui-icon layui-icon-fonts-code",
			            title: "Gitee地址",
			            href: "https://gitee.com/530521314/Partner.Surround.git"
		            }
                ],
                other: {
                    keepLoad: false, // 主 页 加 载 过 度 时 长 可 为 false
                }
            };
            admin.render(config);

			window.selectedWindow = function () {
				return $(".layui-body .layui-tab-content .layui-show")[0].children[0].contentWindow;
            }

            window.openChatPanel = function () {
				chatPanelIndex = layer.open({
                    type: 2,
                    title: "飞鸽传书",
                    content: "@Url.Action("Index", "Chat")",
                    area: ["1000px","643px"],
                    shade: 0.3,
                    shadeClose: true,
                    resize:false,
                    end:function(){
                        chatPanelIndex = "";
                    }
                });
            }

            function loadUnreadNotificationCount() {
                abp.ajax({
                    url: "@Url.Action("GetUnreadNotificationCount", "Notifications")",
                    type: "Get",
                    abpHandleError: false
                }).done(function (data) {
                    if (data.code == 200 && data.data > 0) {
                        notificationUnread();
                    }
                }).fail(function (jqXHR) {
                    layer.msg(jqXHR.message, { icon: 5 });
                });
            }

            function loadUnreadMessageCount() {
                abp.ajax({
                    url: "@Url.Action("GetUnreadMessageCount", "Chat")",
                    type: "Get",
                    abpHandleError: false
                }).done(function (data) {
                    if (data.code == 200 && data.data > 0) {
                        messageReceived();
                    }
                }).fail(function (jqXHR) {
                    layer.msg(jqXHR.message, { icon: 5 });
                });
            }

            $("body").on("click", ".pear-social-entrance", function () {
                openChatPanel();
                clearInterval(interval);
                interval = "";
            });

            $(".notice").click(function () {
                layer.open({
                    type: 2,
                    title: "消息通知",
                    content: "@Url.Action("Index", "Notifications")",
                    area: ["800px","600px"],
                    shade: 0.1
                });
            });

            abp.event.on('app.chat.messageReceived', function (message) {
                messageReceived();
            });

            abp.event.on('abp.notifications.received', function (userNotification) {
                abp.notifications.showUiNotifyForUserNotification(userNotification);
                notificationUnread();
            });

            function notificationUnread() {
                $("#headerNotice").addClass("layui-badge-dot");
            }

            function messageReceived() {
                if (interval == "" && chatPanelIndex == "") {
                    interval = window.setInterval(function(){
                        if ($(".pear-social-entrance").css("display") == "none") {
                            $(".pear-social-entrance").css("display", "");
                        } else {
                            $(".pear-social-entrance").css("display", "none");
                        }
                    }, 500);
                }
            }

            var init = function () {
                loadUnreadNotificationCount();
                loadUnreadMessageCount();
            };
            init();
        });
    </script>
}

src/Partner.Surround.Admin/Views/Home/_Layout.cshtml
@using Abp.Configuration.Startup
@using Abp.Web.Mvc.Alerts
@using Abp.Web.Security.AntiForgery
@inject IAbpAntiForgeryManager AbpAntiForgeryManager
@inject IMultiTenancyConfig MultiTenancyConfig
@inject IAlertManager AlertManager
@inject ILanguageManager LanguageManager
@{
    Layout = null;
    AbpAntiForgeryManager.SetCookie(Context);

    var pageTitle = !string.IsNullOrWhiteSpace(ViewBag.Title) ? ViewBag.Title + " / " : "";
    pageTitle += "Surround";
}

<!DOCTYPE html>
<html lang="@LanguageManager.CurrentLanguage.Name">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@pageTitle</title>
    <link rel="shortcut icon" href="~/images/favicon.ico">
    <link rel="stylesheet" href="~/libs/pear/css/pear.css" asp-append-version="true" />
    <style id="pearadmin-bg-color"></style>
    @RenderSection("styles", required: false)
</head>
<body class="layui-layout-body pear-admin">

    @RenderBody()

    <script src="~/libs/layui/layui.js" asp-append-version="true"></script>
    <script src="~/libs/pear/pear.js" asp-append-version="true"></script>
    <script src="~/libs/signalr/signalr.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>