src/Partner.Surround.Admin/Controllers/TenantsController.cs
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using Microsoft.AspNetCore.Mvc;
using Partner.Surround.Admin.Models.Common;
using Partner.Surround.MultiTenancy.Editions;
using Partner.Surround.MultiTenancy.Tenants;
using Partner.Surround.MultiTenancy.Tenants.Dto;

namespace Partner.Surround.Admin.Controllers
{
    /// <summary>
    /// 多租户控制器
    /// </summary>
    [AbpMvcAuthorize]
    public class TenantsController : SurroundControllerBase
    {
        #region 初始化
        private readonly ITenantAppService _tenantAppService;
        private readonly IEditionAppService _editionAppService;

        public TenantsController(ITenantAppService tenantAppService,
            IEditionAppService editionAppService)
        {
            _tenantAppService = tenantAppService;
            _editionAppService = editionAppService;
        }
        #endregion

        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取租户列表
        /// </summary>
        /// <returns></returns>
        public async Task<JsonResult> GetTenantList()
        {
            var tenantDtos = await _tenantAppService.GetAllTenant();
            return Json(new ResponseParamListViewModel<TenantDto>(tenantDtos.Items));
        }

        /// <summary>
        /// 租户版本变更
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        public async Task<IActionResult> ChangeTenantEdition(EntityDto<int> input)
        {
            var tenant = await _tenantAppService.GetTenantForEdit(input);
            var editionList = await _editionAppService.GetAllEdition();
            ViewBag.EditionList = editionList.Items;

            return View(tenant);
        }

        /// <summary>
        /// 租户版本变更
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> ChangeTenantEdition([FromBody]ChangeTenantEditionDto input)
        {
            await _tenantAppService.ChangeTenantEdition(input);
            return Json(new ResponseParamViewModel(L("EditionChangeSuccessful")));
        }
    }
}

src/Partner.Surround.Admin/Views/Tenants/ChangeTenantEdition.cshtml
@using Abp.Json
@using Partner.Surround.MultiTenancy.Tenants.Dto
@model TenantDto

@section styles{
    <style type="text/css">
        #edition-content {
            width: 100% !important;
            height: 300px;
        }
    </style>
}

<div class="layui-card" id="edition-content">
    <div class="layui-card-body">
        <table id="edition-table" lay-filter="edition-table"></table>
    </div>
</div>

@await Html.PartialAsync("_LastModificationTime")

@section scripts{
    <script type="text/javascript">
        layui.use(['abp', 'form','table'], function () {
            var $ = layui.jquery;
            var abp = layui.abp;
            var form = layui.form,
            var table = layui.table;

            var index = parent.layer.getFrameIndex(window.name);
            parent.layer.iframeAuto(index);

            var editionList = @Html.Raw(JsonExtensions.ToJsonString(ViewBag.EditionList, true, false));

            table.render({
		        elem: '#edition-table',
		        data: editionList,
                limit: editionList.length,
		        cols: [
		            [
		                {type:'radio'},
		                {title: '版本名称', field: 'displayName', align:'center'},
		                {title: '最后修改时间', field: 'lastModificationTime', align:'center',templet:'#lastModificationTime'},
		                {title: '操作', toolbar: '#edition-bar', align:'center', width:130}
		            ]
                ],
                height: 'full',
		        skin: 'line',
                done: function (res, curr, count) {
                    for (var i = 0; i < res.data.length; i++) {
                        //数据id和要勾选的id相同时radio选中
                        if (res.data[i].id == "@Model.EditionId") {
                            //这里才是真正的有效勾选
                            res.data[i]["LAY_CHECKED"] = 'true';
                            //找到对应数据改变勾选样式，呈现出选中效果
                            var index = res.data[i]['LAY_TABLE_INDEX'];
                            $('.layui-table tr[data-index=' + index + '] input[type="radio"]').prop('checked', true);
                            $('.layui-table tr[data-index=' + index + '] input[type="radio"]').next().addClass('layui-form-radioed');

                            form.val();
                            break;
                        }
                    }
                }
		    });

            table.on("row(edition-table)", function (obj) {
                obj.tr.addClass('layui-table-click').siblings().removeClass('layui-table-click');//选中行样式
                obj.tr.find('input[lay-type="layTableRadio"]').prop("checked", true);
                var index = obj.tr.data('index')
                var thisData = table.cache["edition-table"];
                
                //重置数据单选属性
                layui.each(thisData, function (i, item) {
                    if (index === i) {
                        item.LAY_CHECKED = true;
                    } else {
                        delete item.LAY_CHECKED;
                    }
                });
                form.render('radio');
            });

            //触发表单提交
            window.submitForm = function () {
                var checkData = table.checkStatus('edition-table').data;
                if (checkData.length == 0) {
                    parent.layer.msg("请选择版本");
                    return;
                }

                if (checkData[0].id == '@Model.EditionId') {
                    parent.layer.msg("版本未变更，无需更换");
                    return;
                }

                var field = {
                    id: '@Model.Id',
                    sourceEditionId: '@Model.EditionId',
                    targetEditionId: checkData[0].id
                };

                var waitIndex = parent.layer.load(2);
                abp.ajax({
                    url: "@Url.Action("ChangeTenantEdition", "Tenants")",
                    data: JSON.stringify(field),
                    abpHandleError: false
                }).done(function (data) {
                    if (data.code == 200) {
                        data.index = index;
                        let parentWindow = parent.selectedWindow().window;
                        parentWindow.saveCallback(data);
                    }
                }).fail(function (jqXHR) {
                    parent.layer.msg(jqXHR.message, { icon: 5 });
                }).always(function () {
                    parent.layer.close(waitIndex);
                });

                return false;
            };
        });
    </script>
}

src/Partner.Surround.Admin/Views/Tenants/Index.cshtml
@using Partner.Surround.Admin.Views
@using Partner.Surround.Authorization
@{
    ViewBag.CurrentPageName = SurroundPageName.Tenants;
}

<div class="layui-card">
    <div class="layui-card-body">
        <table id="tenant-table" lay-filter="tenant-table"></table>
    </div>
</div>

<script type="text/html" id="tenant-bar">
    @if (await PermissionChecker.IsGrantedAsync(AppPermissionNames.Pages_SystemManagement_Tenants_ChangeTenantEdition))
    {
        <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="edit"><i class="layui-icon layui-icon-edit"></i></button>
    }
</script>

@section scripts{
    <script type="text/javascript">
        layui.use(['abp', 'table'], function () {
            var $ = layui.jquery;
            var abp = layui.abp;
            var table = layui.table;

		    table.render({
		        elem: '#tenant-table',
		        url: "@Url.Action("GetTenantList", "Tenants")",
                page: false,
                height: 'full-70',
                parseData: function (res) {
                    return {
                        "code": res.result.code, //解析接口状态
                        "msg": res.result.msg, //解析提示文本
                        "count": res.result.count, //解析数据长度
                        "data": res.result.data //解析数据列表
                    };
                },
                response: {
                    statusCode: 200 //规定成功的状态码，默认：0
                },
		        cols: [
		            [
		                {title: '租户名称', field: 'tenancyName'},
		                {title: '版本名称', field: 'editionName'},
		                {title: '操作', toolbar: '#tenant-bar', align:'center', width:130}
		            ]
		        ],
		        skin: 'line',
		        toolbar: '#tenant-toolbar',
		        defaultToolbar: [{
		            layEvent: 'refresh',
		            icon: 'layui-icon-refresh',
		        }, 'filter', 'print', 'exports']
		    });

            table.on('tool(tenant-table)', function (obj) {
                var data = obj.data;
		        if(obj.event === 'edit'){
		            window.edit(data);
		        }
		    });

		    table.on('toolbar(tenant-table)', function(obj){
		        if(obj.event === 'refresh'){
		            window.refresh();
		        }
            });

            window.saveCallback = function (data) {
                parent.layer.close(data.index);
                abp.notify.success(data.msg);
                table.reload("tenant-table");
            }

		    window.edit = function(data){
		        parent.layer.open({
                    type: 2,
                    title: "切换版本",
                    content: "@Url.Action("ChangeTenantEdition", "Tenants")" + abp.utils.formatString("?id={0}", data.id),
                    area: ["600px","450px"],
                    shade: 0.1,
                    btn: ['确定', '取消'],
                    yes: function (index, layero) {
                        parent.window['layui-layer-iframe'+ index].submitForm();
                    }
                });
            }

	        window.refresh = function(param){
		        table.reload('tenant-table');
		    }
        });
    </script>
}